### ISSUE TITLE
Doesn't update, no way to manually refresh?

### ISSUE THREAD

**Issue by mindplay-dk** [Symbolk/somanyconflicts#29]
This panel was very useful as far as finding the conflicts I needed to resolve.

Unfortunately, resolved items do not disappear from the list? It doesn't seem to update.

I tried the pull-down menu on the panel, and there doesn't seem to be any way to manually refresh either.

Even after committing, the conflicts stay there - there's no way to clear or refresh them for the next merge? Short of restarting Code.

On a related note, it's not clear to me what the difference is between "suggested conflicts to resolve" and "all merge conflicts" - these lists were identical for me. Which conflicts wouldn't be suggested? When would you not need/want to resolve all the conflicts?

**Comment by Symbolk** [comment]
Thanks for the issue.

The resolved conflicts should be marked with a green mark:

![image](https://user-images.githubusercontent.com/14107297/129534467-92a139a2-8058-4aa9-8ada-72dd75d76db9.png)

If you want to refresh, currently you can press F1 and run `So Many Conflicts: Scan All Merge Conflicts` to rescan (but I agree that a button will be better and will be added):

![image](https://user-images.githubusercontent.com/14107297/129534564-58096660-ade2-47cd-816f-b56670e4cdc6.png)

By design, "suggested conflicts to resolve" shows the groups of conflicts consisting of related ones, and "all merge conflicts" just shows the conflicts in each file.

**Comment by Symbolk** [comment]
I've added the refresh button and explainable text, please update the extension to the latest v0.1.2.

![image](https://user-images.githubusercontent.com/14107297/129849088-77dbe854-fba6-4854-9aa2-5c92dd84ac3d.png)
